### Registro de un nuevo usuario
POST http://localhost:3000/auth/register
Content-Type: application/json

{
  "nombre": "Grace",
  "telefono": "12345678",
  "email": "grace@demo.com",
  "password": "123456789"
}

### Login
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "grace@demo.com",
  "password": "987654321"
}

### Obtener perfil
GET http://localhost:3000/usuario/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Mywicm9sIjoxLCJpYXQiOjE3NTY4NTk2OTMsImV4cCI6MTc1Njg2MzI5M30.l0zVfs69udEDLfijC4QXXk0QpmFvWpZphhzqaqoAGOQ

### Actualizar perfil
PUT http://localhost:3000/usuario/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Mywicm9sIjoxLCJpYXQiOjE3NTY4NTk2OTMsImV4cCI6MTc1Njg2MzI5M30.l0zVfs69udEDLfijC4QXXk0QpmFvWpZphhzqaqoAGOQ
Content-Type: application/json

{
  "nombre": "Joab Ramirez",
  "telefono": "12345678",
  "email": "joab@example.com"
}

### Cambio de Contrasena
PUT http://localhost:3000/usuario/me/password
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Miwicm9sIjoxLCJpYXQiOjE3NTY4NTgyMjUsImV4cCI6MTc1Njg2MTgyNX0.l8meB-WDw9S91ngC_-5RDUFALj5Ul_4hEk3J5pGxTE4
Content-Type: application/json

{
  "currentPassword": "123456789",
  "newPassword": "987654321"
}


### Parte Administrativa
### Login
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "joab@example.com",
  "password": "987654321"
}

### Ver por ID
GET http://localhost:3000/admin/usuarios/3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Miwicm9sIjozLCJpYXQiOjE3NTY4NTk3MzksImV4cCI6MTc1Njg2MzMzOX0.x9eZK0y-9Q6EVVh4v5Kp_F31FwmKVMr3D41OgqXYyyc

### Ver Todos los Usuarios
GET http://localhost:3000/admin/usuarios
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Miwicm9sIjozLCJpYXQiOjE3NTY4NTk3MzksImV4cCI6MTc1Njg2MzMzOX0.x9eZK0y-9Q6EVVh4v5Kp_F31FwmKVMr3D41OgqXYyyc

### Cambiar Rol de Usuario
PUT http://localhost:3000/admin/usuarios/3/rol
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Miwicm9sIjozLCJpYXQiOjE3NTY4NTk3MzksImV4cCI6MTc1Njg2MzMzOX0.x9eZK0y-9Q6EVVh4v5Kp_F31FwmKVMr3D41OgqXYyyc
Content-Type: application/json

{
  "id_rol": 2
}

### Cambiar Estado Activo/Inactivo
PUT http://localhost:3000/admin/usuarios/3/estado
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Miwicm9sIjozLCJpYXQiOjE3NTY4NTk3MzksImV4cCI6MTc1Njg2MzMzOX0.x9eZK0y-9Q6EVVh4v5Kp_F31FwmKVMr3D41OgqXYyyc
Content-Type: application/json

{
  "activo": false
}







### Pedidos
POST http://localhost:3000/pedido
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Mywicm9sIjoyLCJpYXQiOjE3NTY4Njg0ODUsImV4cCI6MTc1Njg3MjA4NX0.-pLnqA121WDZgjcJWeJW_sAGlQCBluY8FUnpvQ2IoMI

{
  "paquete": {
    "descripcion": "Caja con libros",
    "peso": 5.2,
    "dimensiones": "30x20x15 cm",
    "fragil": true
  },
  "direccion_origen": {
    "calle_principal": "1a Avenida",
    "numero": "12",
    "calle_secundaria": "Calle B",
    "zona": "3",
    "colonia_o_barrio": "Colonia Central",
    "municipio": "Ciudad de Guatemala",
    "departamento": "Guatemala",
    "codigo_postal": "01001",
    "referencias": "Frente al parque"
  },
  "direccion_destino": {
    "calle_principal": "5a Avenida",
    "numero": "45",
    "calle_secundaria": "Calle F",
    "zona": "11",
    "colonia_o_barrio": "Colonia La Paz",
    "municipio": "Ciudad de Guatemala",
    "departamento": "Guatemala",
    "codigo_postal": "01011",
    "referencias": "Cerca del mercado"
  },
  "destinatario": {
    "nombre": "Carlos Lopez",
    "email": "carlos@example.com",
    "telefono": "12345678"
  },
  "km_destino": 5
}
