




POST http://localhost:3000/pedido
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Mywicm9sIjoxLCJpYXQiOjE3NTc1NDM0NzQsImV4cCI6MTc1NzU0NzA3NH0.hdjv1QNXdFkFStb-PWqNmgVfLGAyWzTRMF5d-98ns5Q

{
    "paquete": {
        "descripcion": "Paquete electrónico frágil",
        "peso": 2.5,
        "dimensiones": "30x20x10",
        "fragil": true
    },
    "direccion_origen": {
        "calle_principal": "7a Avenida",
        "numero": "12",
        "calle_secundaria": "10a Calle",
        "zona": "1",
        "colonia_o_barrio": "Centro",
        "municipio": "Guatemala",
        "departamento": "Guatemala",
        "codigo_postal": "01001",
        "referencias": "Frente al Parque Central"
    },
    "direccion_destino": {
        "calle_principal": "Boulevard Los Próceres",
        "numero": "20",
        "calle_secundaria": "Calle Real",
        "zona": "10",
        "colonia_o_barrio": "Las Charcas",
        "municipio": "Guatemala",
        "departamento": "Guatemala",
        "codigo_postal": "01010",
        "referencias": "Cerca del centro comercial"
    },
    "destinatario": {
        "nombre": "Ana López",
        "email": "ana.lopez@example.com",
        "telefono": "55551234"
    }
}